# Generated by Django 2.2.1 on 2019-05-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('student_name', models.CharField(max_length=10)),
                ('student_school', models.CharField(max_length=20)),
                ('student_avatar', models.ImageField(upload_to='')),
                ('student_email', models.EmailField(max_length=40, unique=True, verbose_name='email address')),
                ('student_class', models.CharField(max_length=20)),
            ],
        ),
    ]
