# Generated by Django 2.2.1 on 2019-05-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_avatar',
            field=models.CharField(max_length=5000),
        ),
    ]
